- name: copy job.xml file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/s-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: Create a Roboshop jenkins job using basic authentication {{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.47.227:8080
    user: admin

