- name: Create CI pipeline folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{ item }}"
    password: "{{jenkins_password}}"
    url: http://172.31.47.227:80
    user: admin
  loop: "{{ folders }}"


- name: include tasks from m-pipeline.yml
  ansible.builtin.include_tasks: m-pipeline.yml
  loop: "{{pipeline_jobs}}"

- name: include tasks from s-pipeline.yml
  ansible.builtin.include_tasks: s-pipeline.yml
  loop: "{{sbranch_pipeline_jobs}}"