- name: Create CI pipeline folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{ item.dir }}"
    password: "{{jenkins_password}}"
    url: http://172.31.47.227:8080
    user: admin
  loop: "{{ folders }}"


- name: include tasks from pipeline.yml
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{pipeline_jobs}}"

