- name: copy job.xml file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a roboshop jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{ item }}"
    password: "{{jenkins_password}}"
    url: http://172.31.41.63:8080
    user: admin
