- name: copy job.xml file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a Roboshop jenkins job using basic authentication "{{dir}}/{{component}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.47.227:8080
    user: admin
  loop: "{{pipeline_jobs}}"
