- name: copy job.xml file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: Create a Roboshop jenkins job using basic authentication {{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.47.227:8080
    user: admin

