- name: Checking existing - {{item.dir}}/{{item.name}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://jenkins.chandrap.shop:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes


- name: copy job.xml file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  when: out.rc == 3

- name: Create a Roboshop jenkins job using basic authentication {{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://jenkins.chandrap.shop:8080
    user: admin
  when: out.rc == 3

